### ISSUE TITLE
Binding to **/* causes a lot of messages in traces and interferes with other interceptors

### ISSUE THREAD

**Issue by murphybob** [redabacha/polly-adapter-playwright#61]
I've just started using Polly with Playwright and noticed 2 things about the use of **/* interception.

Firstly it seemed to cause a problem with an existing interceptor I had on a more specific route. Depending on the order of attachment polly-playwright-adapter seemed to grab the request and continue it meaning my route interceptor never got a chance so I had to mess around with the order of things to get my test to work again.

Additionally in traces or the (awesome) new UI view I see a lot of `route.continue()` because I'm only recording a small subset of my requests using `shouldHandleRequest`.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/1550045/228014456-3622538b-87a4-4df2-9e4d-aa0926bca5f3.png">

Would you consider allowing for configuration of the route pattern that this adapter attaches to?  I'm happy to create a PR for it if so.

p.s. Absolutely love this, it's great, thank you so much for creating it!

**Comment by redabacha** [comment]
hey @murphybob,

no problem, thanks for raising this issue and shedding light on the problem! i'd be onboard with adding an extra configuration option to customize the route pattern used for interception - a pr would be totally welcome and appreciated for this.

**Comment by murphybob** [comment]
Thanks 👍 I’m on holiday this week, I’ll put something together next week.

**Comment by testing-onetwo** [comment]
Any movement on this?

**Comment by redabacha** [comment]
sorry i haven't checked on this in a while. i've introduced a new option now called `routesToIntercept` which will let you configure this.

merry christmas! :christmas_tree:
