### ISSUE TITLE
More control of how missing requests are handled

### ISSUE THREAD

**Issue by cristinecula** [redabacha/polly-adapter-playwright#88]
Hi! :wave: 

Firstly, thanks for your work on this project! :heart: 

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `polly-adapter-playwright@2.3.0` for the project I'm working on.

I wanted to control the way in which polly handles the requests that are missing from the recording.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/polly-adapter-playwright/dist/PlaywrightAdapter.js b/node_modules/polly-adapter-playwright/dist/PlaywrightAdapter.js
index aadc63f..a9a0437 100644
--- a/node_modules/polly-adapter-playwright/dist/PlaywrightAdapter.js
+++ b/node_modules/polly-adapter-playwright/dist/PlaywrightAdapter.js
@@ -32,6 +32,7 @@ class PlaywrightAdapter extends adapter_1.default {
                 ...response,
                 headers: { ...response.headers, "access-control-allow-origin": "*" },
             }),
+            handleMissing: (pollyRequest, error, route) => route.abort(),
             routesToIntercept: "**/*",
             shouldHandleRequest: (request) => ["fetch", "xhr"].includes(request.resourceType()),
         };
@@ -73,7 +74,7 @@ class PlaywrightAdapter extends adapter_1.default {
     async onRespond(pollyRequest, error) {
         const { requestArguments: { request, route }, response, } = pollyRequest;
         if (error) {
-            return route.abort();
+            return this.options.handleMissing(pollyRequest, error, route)
         }
         let body;
         if (response?.body) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by redabacha** [comment]
hi @cristinecula,

thanks for bringing awareness to the patch you've made. have you considered using the `requestfailed` page event from playwright to be notified of when intercepted routes are aborted, https://playwright.dev/docs/api/class-page#page-event-request-failed? or are you doing something in `handleMissing` which doesn't call `route.abort()`? it would be interesting to hear about your use case for this.

thanks,
reda

**Comment by cristinecula** [comment]
You are right. Basically my `handleMissing` does not do anything. I just want the missing requests to never finish, instead of aborting them.

A bit more detail: 

During testing I don't want to touch the server at all, only replay the requests in the HAR. I am also generating the recordings with the same tests. I run the tests once in a while with `record` mode and then I re-run them very often with `replay` mode. Sometimes I get requests that are missing from the HAR, either because they are only requested during the `replay` mode (I'm also speeding up the replay timing, which causes inconsistencies in the requests), or because they were in transit when the test finished. The missing requests get aborted, but due to how the website is made, parts of the UI become unavailable because of the request failure. This fix enables me to configure the adapter to not abort the requests, but instead to leave them in transit, such that the UI does not hide the stuff I'm testing. Does that make sense? 

I implemented it as a function, because you could also, theoretically, want to respond with a fabricated 404 error message.

**Comment by redabacha** [comment]
thanks for the thorough explanation @cristinecula, much appreciated. i've added a new `handleFailingRequest` option for you that should accomodate your use case. i renamed it from `handleMissing` as it's possible for aborted requests and other unknown errors to also trigger this handler too.

**Comment by cristinecula** [comment]
Thank you very much! 🙏
